### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by Allenhe123** [storypku/storydev#1]
Hi Jiaming,

I have some questions and had sent an email to your gmail.
Could you please read it and give some comments?

Thanks a lot in advance.

**Comment by storypku** [comment]
OK，I will check it ASAP.

**Comment by Allenhe123** [comment]
Hi Jiaming,


Thank you for your response.
Actually, i have got the answer from one of your&nbsp;colleagues :).
Anyway, thank you very much.
PS: Would you mind to share your wechat to me?


Thanks again.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Liu Jiaming"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月11日(星期四) 下午4:22
收件人:&nbsp;"storypku/storydev"<storydev@noreply.github.com&gt;;
抄送:&nbsp;"浓浓の拳拳"<931317255@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [storypku/storydev] some questions (#1)





 
OK，I will check it ASAP.
